[monitoring_stack]
localhost ansible_connection=local

[monitoring_stack:vars]
prometheus_url=http://localhost:9090
grafana_url=http://localhost:3000
grafana_user=admin
alertmanager_url=http://localhost:9093
env=dev